import mongoose from "mongoose";

// ============================================================
// LESSONS (5 modules)
// ============================================================
export const lessons = [
  {
    title: "Intro to Python",
    description: "Get started with Python programming. Learn what Python is, how to run your first program, and understand the print() function.",
    topic: "overview",
    order: 0,
  },
  {
    title: "Data Types and Variables",
    description: "Learn about Python's core data types including integers, floats, strings, and booleans, and how to store values in variables.",
    topic: "variables",
    order: 1,
  },
  {
    title: "Operators",
    description: "Explore arithmetic, comparison, and logical operators to perform calculations and evaluate expressions in Python.",
    topic: "operators",
    order: 2,
  },
  {
    title: "Conditionals",
    description: "Control the flow of your program using if, elif, and else statements to make decisions based on conditions.",
    topic: "conditionals",
    order: 3,
  },
  {
    title: "Loops",
    description: "Repeat actions efficiently using while loops to iterate through tasks and automate repetitive operations.",
    topic: "loops",
    order: 4,
  },
];

// ============================================================
// LESSON MATERIALS
// lessonId will be injected at seed time
// ============================================================
export const lessonMaterials = [
  // ── MODULE 0: Intro to Python ─────────────────────────────
  {
    lessonKey: "Intro to Python",
    title: "What is Python?",
    overview: "A brief introduction to the Python programming language and why it is widely used.",
    contents: [
      "Python is a high-level, interpreted programming language known for its simple and readable syntax.",
      "It was created by Guido van Rossum and first released in 1991.",
      "Python is used in web development, data science, artificial intelligence, automation, and more.",
      "Python code is written in plain text files with the .py extension.",
      "Python runs one line at a time from top to bottom, making it easy to follow and debug.",
    ],
    order: 0,
  },
  {
    lessonKey: "Intro to Python",
    title: "Your First Python Program: print()",
    overview: "Learn how to display output to the screen using the print() function.",
    contents: [
      "The print() function is used to display output to the screen.",
      "Syntax: print(value) — place what you want to show inside the parentheses.",
      "To print text (a string), wrap it in quotes: print('Hello, World!')",
      "To print a number, write it directly without quotes: print(42)",
      "You can print multiple values by separating them with commas: print('Age:', 25)",
      "Every print() call outputs on its own new line by default.",
      "Example:\n  print('Hello')\n  print('World')\nOutput:\n  Hello\n  World",
    ],
    order: 1,
  },
  {
    lessonKey: "Intro to Python",
    title: "Python Comments",
    overview: "Understand how to write comments in Python to document your code.",
    contents: [
      "A comment is a line in your code that Python ignores when running the program.",
      "Comments are used to explain what your code does.",
      "In Python, a comment starts with the # symbol.",
      "Example: # This prints a greeting\n  print('Hello')",
      "Comments can be placed on their own line or at the end of a line of code.",
      "Good comments make code easier to understand for yourself and others.",
    ],
    order: 2,
  },

  // ── MODULE 1: Data Types and Variables ────────────────────
  {
    lessonKey: "Data Types and Variables",
    title: "Introduction to Variables",
    overview: "Understand what variables are and how to create them in Python.",
    contents: [
      "A variable is a named container that stores a value in your program.",
      "You create a variable by writing a name, then = , then the value: age = 25",
      "Variable names must start with a letter or underscore, not a number.",
      "Variable names are case-sensitive: name and Name are different variables.",
      "Once created, you can use the variable name anywhere you need its value.",
      "Example:\n  city = 'Manila'\n  print(city)\nOutput:\n  Manila",
    ],
    order: 0,
  },
  {
    lessonKey: "Data Types and Variables",
    title: "Integers and Floats",
    overview: "Learn about numeric data types: whole numbers and decimal numbers.",
    contents: [
      "An integer (int) is a whole number with no decimal point: 5, -3, 100",
      "A float is a number with a decimal point: 3.14, -0.5, 100.0",
      "You can assign them to variables: score = 95  or  price = 19.99",
      "Use print() to display them: print(score) outputs 95",
      "Python automatically determines the type based on the value you assign.",
      "Example:\n  temperature = 36.6\n  print(temperature)\nOutput:\n  36.6",
    ],
    order: 1,
  },
  {
    lessonKey: "Data Types and Variables",
    title: "Strings",
    overview: "Learn about text data in Python using strings.",
    contents: [
      "A string is a sequence of characters enclosed in single or double quotes.",
      "Examples: 'hello', \"Python\", 'My name is Ana'",
      "Strings can be assigned to variables: name = 'Jose'",
      "Print a string variable: print(name) outputs Jose",
      "You can combine strings and variables in print(): print('Hello', name)",
      "Strings can include letters, numbers, spaces, and special characters.",
      "Example:\n  greeting = 'Good morning'\n  print(greeting)\nOutput:\n  Good morning",
    ],
    order: 2,
  },
  {
    lessonKey: "Data Types and Variables",
    title: "Booleans",
    overview: "Learn about the boolean data type which holds True or False values.",
    contents: [
      "A boolean (bool) can only be one of two values: True or False.",
      "Booleans are used to represent yes/no or on/off conditions.",
      "Assign them like any variable: is_raining = True",
      "Note: True and False must start with a capital letter in Python.",
      "Print a boolean: print(is_raining) outputs True",
      "Example:\n  has_passed = False\n  print(has_passed)\nOutput:\n  False",
    ],
    order: 3,
  },

  // ── MODULE 2: Operators ───────────────────────────────────
  {
    lessonKey: "Operators",
    title: "Arithmetic Operators",
    overview: "Perform mathematical calculations using Python's arithmetic operators.",
    contents: [
      "Arithmetic operators let you do math in Python.",
      "+ adds two values: 5 + 3 equals 8",
      "- subtracts: 10 - 4 equals 6",
      "* multiplies: 3 * 7 equals 21",
      "/ divides and always returns a float: 10 / 2 equals 5.0",
      "// is floor division (drops decimal): 10 // 3 equals 3",
      "% is modulo (remainder): 10 % 3 equals 1",
      "** is exponentiation (power): 2 ** 3 equals 8",
      "Example:\n  result = 10 + 5\n  print(result)\nOutput:\n  15",
    ],
    order: 0,
  },
  {
    lessonKey: "Operators",
    title: "Comparison Operators",
    overview: "Compare values using comparison operators that return True or False.",
    contents: [
      "Comparison operators compare two values and return True or False.",
      "== checks if two values are equal: 5 == 5 is True",
      "!= checks if two values are not equal: 5 != 3 is True",
      "< checks if left is less than right: 3 < 7 is True",
      "<= checks less than or equal: 5 <= 5 is True",
      "> checks if left is greater than right: 9 > 4 is True",
      ">= checks greater than or equal: 6 >= 6 is True",
      "Example:\n  x = 10\n  print(x > 5)\nOutput:\n  True",
    ],
    order: 1,
  },
  {
    lessonKey: "Operators",
    title: "Using Operators with Variables",
    overview: "Apply arithmetic and comparison operators using variables.",
    contents: [
      "You can use variables on both sides of any operator.",
      "Store the result of a calculation in a new variable: total = price + tax",
      "You can update a variable using itself: count = count + 1",
      "Shorthand update operators: count += 1 means count = count + 1",
      "Similarly: x -= 2, x *= 3, x /= 4 all work the same way.",
      "Example:\n  a = 8\n  b = 3\n  print(a - b)\nOutput:\n  5",
    ],
    order: 2,
  },

  // ── MODULE 3: Conditionals ────────────────────────────────
  {
    lessonKey: "Conditionals",
    title: "The if Statement",
    overview: "Learn how to run code only when a condition is True using if.",
    contents: [
      "An if statement runs a block of code only when the condition is True.",
      "Syntax:\n  if condition:\n      # code to run",
      "The condition is usually a comparison expression like x > 5.",
      "The code inside the if block must be indented (4 spaces or 1 tab).",
      "If the condition is False, the indented block is skipped entirely.",
      "Example:\n  age = 18\n  if age >= 18:\n      print('Adult')\nOutput:\n  Adult",
    ],
    order: 0,
  },
  {
    lessonKey: "Conditionals",
    title: "The else Statement",
    overview: "Provide an alternative code block when the if condition is False.",
    contents: [
      "The else block runs when the if condition is False.",
      "Syntax:\n  if condition:\n      # runs if True\n  else:\n      # runs if False",
      "Only one of the two blocks will ever run.",
      "else does not have its own condition — it is a catch-all.",
      "Example:\n  score = 40\n  if score >= 50:\n      print('Pass')\n  else:\n      print('Fail')\nOutput:\n  Fail",
    ],
    order: 1,
  },
  {
    lessonKey: "Conditionals",
    title: "The elif Statement",
    overview: "Check multiple conditions in sequence using elif.",
    contents: [
      "elif stands for 'else if' and lets you check additional conditions.",
      "Syntax:\n  if condition1:\n      # block 1\n  elif condition2:\n      # block 2\n  else:\n      # block 3",
      "Python checks each condition in order and runs only the first matching block.",
      "You can have as many elif blocks as needed.",
      "The else at the end is optional but handles all remaining cases.",
      "Example:\n  grade = 85\n  if grade >= 90:\n      print('A')\n  elif grade >= 80:\n      print('B')\n  else:\n      print('C')\nOutput:\n  B",
    ],
    order: 2,
  },

  // ── MODULE 4: Loops ───────────────────────────────────────
  {
    lessonKey: "Loops",
    title: "Introduction to while Loops",
    overview: "Repeat a block of code as long as a condition remains True.",
    contents: [
      "A while loop repeats a block of code as long as the condition is True.",
      "Syntax:\n  while condition:\n      # code to repeat",
      "The condition is checked before each iteration.",
      "When the condition becomes False, the loop stops.",
      "Make sure the condition eventually becomes False, or the loop runs forever.",
      "Example:\n  i = 1\n  while i <= 3:\n      print(i)\n      i += 1\nOutput:\n  1\n  2\n  3",
    ],
    order: 0,
  },
  {
    lessonKey: "Loops",
    title: "Controlling Loops with a Counter",
    overview: "Use a counter variable to control how many times a loop runs.",
    contents: [
      "A counter is a variable that tracks how many times the loop has run.",
      "Initialize the counter before the loop: count = 0",
      "Increment it inside the loop: count += 1",
      "Use the counter in the condition to stop at the right time: while count < 5",
      "You can also print the counter to see loop progress.",
      "Example:\n  count = 0\n  while count < 3:\n      print('Hello')\n      count += 1\nOutput:\n  Hello\n  Hello\n  Hello",
    ],
    order: 1,
  },
  {
    lessonKey: "Loops",
    title: "Loops with Accumulation",
    overview: "Use a while loop to accumulate a total or build a result.",
    contents: [
      "Accumulation means building up a value across multiple loop iterations.",
      "Initialize your accumulator variable before the loop: total = 0",
      "Add to it inside the loop: total += i",
      "After the loop ends, the accumulator holds the final result.",
      "This pattern is used for summing numbers, counting items, and more.",
      "Example:\n  total = 0\n  i = 1\n  while i <= 4:\n      total += i\n      i += 1\n  print(total)\nOutput:\n  10",
    ],
    order: 2,
  },
];

// ============================================================
// LESSON ACTIVITIES
// materialId will be injected at seed time
// ============================================================
export const lessonActivities = [
  // ── MODULE 0 ACTIVITIES ───────────────────────────────────
  {
    materialKey: "Your First Python Program: print()",
    name: "Print Your Name",
    instructions: "Use the print() function to display your first name on the screen.",
    hints: ["Use print() with your name inside quotes.", "Example: print('Maria')"],
    expectedOutput: "Maria",
    difficulty: "easy",
    timeLimit: 60,
    order: 0,
    dataTypesRequired: ["print"],
  },
  {
    materialKey: "Your First Python Program: print()",
    name: "Print a Number",
    instructions: "Use print() to display the number 7 on the screen.",
    hints: ["Numbers do not need quotes inside print().", "print(7)"],
    expectedOutput: "7",
    difficulty: "easy",
    timeLimit: 60,
    order: 1,
    dataTypesRequired: ["print"],
  },
  {
    materialKey: "Your First Python Program: print()",
    name: "Print Two Lines",
    instructions: "Print the word Hello on the first line and the word Python on the second line using two separate print() statements.",
    hints: ["Call print() twice.", "Each print() call creates a new line."],
    expectedOutput: "Hello\nPython",
    difficulty: "easy",
    timeLimit: 90,
    order: 2,
    dataTypesRequired: ["print"],
  },
  {
    materialKey: "Your First Python Program: print()",
    name: "Print a Sentence",
    instructions: "Use print() to display the sentence: I love Python",
    hints: ["Put the full sentence inside quotes.", "print('I love Python')"],
    expectedOutput: "I love Python",
    difficulty: "easy",
    timeLimit: 60,
    order: 3,
    dataTypesRequired: ["print"],
  },

  // ── MODULE 1 ACTIVITIES ───────────────────────────────────
  {
    materialKey: "Introduction to Variables",
    name: "Store and Print a Name",
    instructions: "Create a variable called name and assign your first name to it. Then print the variable.",
    hints: ["name = 'your name here'", "Then use print(name)"],
    expectedOutput: "Ana",
    difficulty: "easy",
    timeLimit: 90,
    order: 0,
    dataTypesRequired: ["variable", "print"],
  },
  {
    materialKey: "Introduction to Variables",
    name: "Store and Print a City",
    instructions: "Create a variable called city with the value Manila and print it.",
    hints: ["Assign: city = 'Manila'", "Then: print(city)"],
    expectedOutput: "Manila",
    difficulty: "easy",
    timeLimit: 90,
    order: 1,
    dataTypesRequired: ["variable", "print"],
  },
  {
    materialKey: "Integers and Floats",
    name: "Store an Integer",
    instructions: "Create a variable called score with the value 95 and print it.",
    hints: ["score = 95", "print(score)"],
    expectedOutput: "95",
    difficulty: "easy",
    timeLimit: 90,
    order: 0,
    dataTypesRequired: ["variable", "print"],
  },
  {
    materialKey: "Integers and Floats",
    name: "Store a Float",
    instructions: "Create a variable called temperature with the value 36.6 and print it.",
    hints: ["temperature = 36.6", "print(temperature)"],
    expectedOutput: "36.6",
    difficulty: "easy",
    timeLimit: 90,
    order: 1,
    dataTypesRequired: ["variable", "print"],
  },
  {
    materialKey: "Strings",
    name: "Greeting Variable",
    instructions: "Create a variable called greeting with the value Good morning and print it.",
    hints: ["greeting = 'Good morning'", "print(greeting)"],
    expectedOutput: "Good morning",
    difficulty: "easy",
    timeLimit: 90,
    order: 0,
    dataTypesRequired: ["variable", "print"],
  },
  {
    materialKey: "Booleans",
    name: "Boolean Variable",
    instructions: "Create a variable called is_sunny with the value True and print it.",
    hints: ["is_sunny = True", "Remember: capital T in True"],
    expectedOutput: "True",
    difficulty: "easy",
    timeLimit: 90,
    order: 0,
    dataTypesRequired: ["variable", "print"],
  },

  // ── MODULE 2 ACTIVITIES ───────────────────────────────────
  {
    materialKey: "Arithmetic Operators",
    name: "Add Two Numbers",
    instructions: "Create variables a = 12 and b = 8. Print the result of adding them.",
    hints: ["result = a + b", "print(result)"],
    expectedOutput: "20",
    difficulty: "easy",
    timeLimit: 120,
    order: 0,
    dataTypesRequired: ["variable", "add", "print"],
  },
  {
    materialKey: "Arithmetic Operators",
    name: "Subtract Two Numbers",
    instructions: "Create variables x = 20 and y = 7. Print the result of subtracting y from x.",
    hints: ["result = x - y", "print(result)"],
    expectedOutput: "13",
    difficulty: "easy",
    timeLimit: 120,
    order: 1,
    dataTypesRequired: ["variable", "subtract", "print"],
  },
  {
    materialKey: "Arithmetic Operators",
    name: "Multiply Two Numbers",
    instructions: "Create variables p = 6 and q = 4. Print the result of multiplying them.",
    hints: ["result = p * q", "print(result)"],
    expectedOutput: "24",
    difficulty: "easy",
    timeLimit: 120,
    order: 2,
    dataTypesRequired: ["variable", "multiple", "print"],
  },
  {
    materialKey: "Arithmetic Operators",
    name: "Divide Two Numbers",
    instructions: "Create variables m = 15 and n = 3. Print the result of dividing m by n.",
    hints: ["result = m / n", "Division always returns a float."],
    expectedOutput: "5.0",
    difficulty: "easy",
    timeLimit: 120,
    order: 3,
    dataTypesRequired: ["variable", "divide", "print"],
  },
  {
    materialKey: "Comparison Operators",
    name: "Equal Comparison",
    instructions: "Create a variable x = 10. Print the result of checking if x equals 10.",
    hints: ["print(x == 10)", "This will print True or False."],
    expectedOutput: "True",
    difficulty: "easy",
    timeLimit: 120,
    order: 0,
    dataTypesRequired: ["variable", "equal", "print"],
  },
  {
    materialKey: "Comparison Operators",
    name: "Greater Than Comparison",
    instructions: "Create variables a = 15 and b = 9. Print the result of checking if a is greater than b.",
    hints: ["print(a > b)"],
    expectedOutput: "True",
    difficulty: "easy",
    timeLimit: 120,
    order: 1,
    dataTypesRequired: ["variable", "greater", "print"],
  },
  {
    materialKey: "Using Operators with Variables",
    name: "Running Total",
    instructions: "Start with total = 10. Add 5 to total using +=. Print total.",
    hints: ["total += 5", "print(total)"],
    expectedOutput: "15",
    difficulty: "medium",
    timeLimit: 150,
    order: 0,
    dataTypesRequired: ["variable", "add", "print"],
  },

  // ── MODULE 3 ACTIVITIES ───────────────────────────────────
  {
    materialKey: "The if Statement",
    name: "Check if Adult",
    instructions: "Create a variable age = 20. Use an if statement: if age is greater than or equal to 18, print Adult.",
    hints: ["if age >= 18:", "    print('Adult')"],
    expectedOutput: "Adult",
    difficulty: "easy",
    timeLimit: 150,
    order: 0,
    dataTypesRequired: ["variable", "if", "greaterequal", "print"],
  },
  {
    materialKey: "The if Statement",
    name: "Positive Number Check",
    instructions: "Create a variable num = 5. If num is greater than 0, print Positive.",
    hints: ["if num > 0:", "    print('Positive')"],
    expectedOutput: "Positive",
    difficulty: "easy",
    timeLimit: 150,
    order: 1,
    dataTypesRequired: ["variable", "if", "greater", "print"],
  },
  {
    materialKey: "The else Statement",
    name: "Pass or Fail",
    instructions: "Create a variable score = 45. If score is greater than or equal to 50, print Pass. Otherwise print Fail.",
    hints: ["if score >= 50:", "else:"],
    expectedOutput: "Fail",
    difficulty: "easy",
    timeLimit: 150,
    order: 0,
    dataTypesRequired: ["variable", "if", "else", "greaterequal", "print"],
  },
  {
    materialKey: "The else Statement",
    name: "Even or Odd",
    instructions: "Create a variable n = 7. If n % 2 equals 0, print Even. Otherwise print Odd.",
    hints: ["Use the % operator to get the remainder.", "if n % 2 == 0:"],
    expectedOutput: "Odd",
    difficulty: "medium",
    timeLimit: 180,
    order: 1,
    dataTypesRequired: ["variable", "if", "else", "equal", "print"],
  },
  {
    materialKey: "The elif Statement",
    name: "Grade Checker",
    instructions: "Create a variable grade = 72. If grade >= 90 print A. elif grade >= 80 print B. elif grade >= 70 print C. else print F.",
    hints: ["Chain if, elif, elif, else.", "Each condition is checked in order."],
    expectedOutput: "C",
    difficulty: "medium",
    timeLimit: 210,
    order: 0,
    dataTypesRequired: ["variable", "if", "elif", "else", "greaterequal", "print"],
  },
  {
    materialKey: "The elif Statement",
    name: "Temperature Description",
    instructions: "Create a variable temp = 15. If temp >= 30 print Hot. elif temp >= 20 print Warm. else print Cold.",
    hints: ["Start with the highest condition.", "Use elif for the middle range."],
    expectedOutput: "Cold",
    difficulty: "medium",
    timeLimit: 210,
    order: 1,
    dataTypesRequired: ["variable", "if", "elif", "else", "greaterequal", "print"],
  },

  // ── MODULE 4 ACTIVITIES ───────────────────────────────────
  {
    materialKey: "Introduction to while Loops",
    name: "Count to 3",
    instructions: "Use a while loop to print the numbers 1, 2, and 3, each on a new line.",
    hints: ["Start i = 1", "Loop while i <= 3, then increment i += 1"],
    expectedOutput: "1\n2\n3",
    difficulty: "easy",
    timeLimit: 180,
    order: 0,
    dataTypesRequired: ["variable", "while", "lessequal", "print"],
  },
  {
    materialKey: "Introduction to while Loops",
    name: "Count Down",
    instructions: "Use a while loop starting at i = 5. While i is greater than 0, print i then subtract 1 from i.",
    hints: ["i = 5", "while i > 0: print(i), i -= 1"],
    expectedOutput: "5\n4\n3\n2\n1",
    difficulty: "easy",
    timeLimit: 180,
    order: 1,
    dataTypesRequired: ["variable", "while", "greater", "print"],
  },
  {
    materialKey: "Controlling Loops with a Counter",
    name: "Print Hello 3 Times",
    instructions: "Use a counter variable starting at 0. While the counter is less than 3, print Hello and increment the counter.",
    hints: ["count = 0", "while count < 3:", "    print('Hello')\n    count += 1"],
    expectedOutput: "Hello\nHello\nHello",
    difficulty: "easy",
    timeLimit: 180,
    order: 0,
    dataTypesRequired: ["variable", "while", "less", "print"],
  },
  {
    materialKey: "Controlling Loops with a Counter",
    name: "Even Numbers up to 10",
    instructions: "Use a while loop. Start at i = 2. While i <= 10, print i then add 2 to i.",
    hints: ["i = 2", "while i <= 10:", "    print(i)\n    i += 2"],
    expectedOutput: "2\n4\n6\n8\n10",
    difficulty: "medium",
    timeLimit: 210,
    order: 1,
    dataTypesRequired: ["variable", "while", "lessequal", "add", "print"],
  },
  {
    materialKey: "Loops with Accumulation",
    name: "Sum 1 to 5",
    instructions: "Use a while loop to calculate the sum of numbers from 1 to 5. Print the total.",
    hints: ["total = 0, i = 1", "while i <= 5: total += i, i += 1", "print(total)"],
    expectedOutput: "15",
    difficulty: "medium",
    timeLimit: 240,
    order: 0,
    dataTypesRequired: ["variable", "while", "add", "lessequal", "print"],
  },
  {
    materialKey: "Loops with Accumulation",
    name: "Multiply Accumulation",
    instructions: "Start with result = 1 and i = 1. While i <= 4, multiply result by i and increment i. Print result.",
    hints: ["result *= i inside the loop", "This computes 1 * 2 * 3 * 4"],
    expectedOutput: "24",
    difficulty: "hard",
    timeLimit: 300,
    order: 1,
    dataTypesRequired: ["variable", "while", "multiple", "lessequal", "print"],
  },
];

// ============================================================
// ASSESSMENTS (question banks per lesson)
// lessonId will be injected at seed time
// ============================================================
export const assessments = [
  // ── MODULE 0: Intro to Python ─────────────────────────────
  {
    lessonKey: "Intro to Python",
    title: "Intro to Python – Print Statement Question Bank",
    timeLimit: 600,
    questions: [
      { instructions: "Print Hello to the screen.", hints: ["Use print()", "Put text in quotes"], expectedOutput: "Hello", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print World to the screen.", hints: ["Use print()", "Put text in quotes"], expectedOutput: "World", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print the number 5 to the screen.", hints: ["Use print()", "Numbers don't need quotes"], expectedOutput: "5", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print the number 10 to the screen.", hints: ["Use print()", "Numbers don't need quotes"], expectedOutput: "10", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print the number 42 to the screen.", hints: ["Use print()", "Numbers don't need quotes"], expectedOutput: "42", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print the text Python to the screen.", hints: ["Use print()", "Wrap text in quotes"], expectedOutput: "Python", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print the text Hello, World! to the screen.", hints: ["Use print()", "Include the comma and exclamation mark"], expectedOutput: "Hello, World!", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print the number 100 to the screen.", hints: ["Use print()", "No quotes needed for numbers"], expectedOutput: "100", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print the text Good morning to the screen.", hints: ["Use print()", "Use quotes around the text"], expectedOutput: "Good morning", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print the text I love coding to the screen.", hints: ["Use print()", "Include spaces inside quotes"], expectedOutput: "I love coding", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print the number 0 to the screen.", hints: ["Use print()", "print(0)"], expectedOutput: "0", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print the text Python is fun to the screen.", hints: ["Use print()"], expectedOutput: "Python is fun", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print the number 999 to the screen.", hints: ["Use print()"], expectedOutput: "999", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print your favorite color (use Blue as the answer).", hints: ["print('Blue')"], expectedOutput: "Blue", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print the text Hello on the first line and World on the second line.", hints: ["Use two separate print() calls", "Each print goes on its own line"], expectedOutput: "Hello\nWorld", difficulty: "Medium", dataTypesRequired: ["print"] },
      { instructions: "Print the numbers 1, 2, and 3 each on their own line.", hints: ["Use three print() statements"], expectedOutput: "1\n2\n3", difficulty: "Medium", dataTypesRequired: ["print"] },
      { instructions: "Print the text Start on the first line and End on the second line.", hints: ["Two print() calls"], expectedOutput: "Start\nEnd", difficulty: "Medium", dataTypesRequired: ["print"] },
      { instructions: "Print the number 3.14 to the screen.", hints: ["Floats don't need quotes"], expectedOutput: "3.14", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print True to the screen.", hints: ["print(True) — capital T"], expectedOutput: "True", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print False to the screen.", hints: ["print(False) — capital F"], expectedOutput: "False", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print the text Welcome to Python! to the screen.", hints: ["Use print()"], expectedOutput: "Welcome to Python!", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print the text My name is Ana to the screen.", hints: ["Use quotes around the text"], expectedOutput: "My name is Ana", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print the number 7 to the screen.", hints: ["print(7)"], expectedOutput: "7", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print the number 55 to the screen.", hints: ["print(55)"], expectedOutput: "55", difficulty: "Easy", dataTypesRequired: ["print"] },
      { instructions: "Print the text Done! to the screen.", hints: ["Include the exclamation mark"], expectedOutput: "Done!", difficulty: "Easy", dataTypesRequired: ["print"] },
    ],
  },

  // ── MODULE 1: Data Types and Variables ────────────────────
  {
    lessonKey: "Data Types and Variables",
    title: "Data Types and Variables – Question Bank",
    timeLimit: 600,
    questions: [
      { instructions: "Create a variable called name with the value Ana. Print name.", hints: ["name = 'Ana'", "print(name)"], expectedOutput: "Ana", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called age with the value 20. Print age.", hints: ["age = 20", "print(age)"], expectedOutput: "20", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called city with the value Manila. Print city.", hints: ["city = 'Manila'", "print(city)"], expectedOutput: "Manila", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called score with the value 95. Print score.", hints: ["score = 95", "print(score)"], expectedOutput: "95", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called price with the value 19.99. Print price.", hints: ["price = 19.99", "print(price)"], expectedOutput: "19.99", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called is_raining with the value False. Print is_raining.", hints: ["is_raining = False", "print(is_raining)"], expectedOutput: "False", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called greeting with the value Hello, World!. Print greeting.", hints: ["greeting = 'Hello, World!'"], expectedOutput: "Hello, World!", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called temp with the value 36.6. Print temp.", hints: ["temp = 36.6", "print(temp)"], expectedOutput: "36.6", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called is_sunny with the value True. Print is_sunny.", hints: ["is_sunny = True", "Capital T"], expectedOutput: "True", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called country with the value Philippines. Print country.", hints: ["country = 'Philippines'"], expectedOutput: "Philippines", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called year with the value 2024. Print year.", hints: ["year = 2024", "print(year)"], expectedOutput: "2024", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called pi with the value 3.14159. Print pi.", hints: ["pi = 3.14159"], expectedOutput: "3.14159", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create two variables: first = 10 and second = 20. Print first, then print second.", hints: ["Two separate print() calls"], expectedOutput: "10\n20", difficulty: "Medium", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called language with the value Python. Print the variable.", hints: ["language = 'Python'"], expectedOutput: "Python", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called count with the value 0. Print count.", hints: ["count = 0", "print(count)"], expectedOutput: "0", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called message with the value Keep going!. Print message.", hints: ["message = 'Keep going!'"], expectedOutput: "Keep going!", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called height with the value 5.9. Print height.", hints: ["height = 5.9"], expectedOutput: "5.9", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called is_valid with the value True. Print is_valid.", hints: ["is_valid = True"], expectedOutput: "True", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called student with the value Ben. Print student.", hints: ["student = 'Ben'"], expectedOutput: "Ben", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called total with the value 500. Print total.", hints: ["total = 500", "print(total)"], expectedOutput: "500", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable x = 3 and a variable y = 4. Print x and then print y.", hints: ["Two print() calls"], expectedOutput: "3\n4", difficulty: "Medium", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called subject with the value Math. Print subject.", hints: ["subject = 'Math'"], expectedOutput: "Math", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called discount with the value 0.25. Print discount.", hints: ["discount = 0.25"], expectedOutput: "0.25", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called flag with the value False. Print flag.", hints: ["flag = False"], expectedOutput: "False", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
      { instructions: "Create a variable called num with the value 77. Print num.", hints: ["num = 77", "print(num)"], expectedOutput: "77", difficulty: "Easy", dataTypesRequired: ["variable", "print"] },
    ],
  },

  // ── MODULE 2: Operators ───────────────────────────────────
  {
    lessonKey: "Operators",
    title: "Operators – Question Bank",
    timeLimit: 600,
    questions: [
      { instructions: "Create a = 5 and b = 3. Print the result of adding a and b.", hints: ["result = a + b", "print(result)"], expectedOutput: "8", difficulty: "Easy", dataTypesRequired: ["variable", "add", "print"] },
      { instructions: "Create x = 10 and y = 4. Print the result of subtracting y from x.", hints: ["result = x - y"], expectedOutput: "6", difficulty: "Easy", dataTypesRequired: ["variable", "subtract", "print"] },
      { instructions: "Create p = 6 and q = 7. Print the result of multiplying them.", hints: ["result = p * q"], expectedOutput: "42", difficulty: "Easy", dataTypesRequired: ["variable", "multiple", "print"] },
      { instructions: "Create m = 20 and n = 4. Print the result of dividing m by n.", hints: ["result = m / n", "Division returns a float"], expectedOutput: "5.0", difficulty: "Easy", dataTypesRequired: ["variable", "divide", "print"] },
      { instructions: "Create a = 8 and b = 2. Print the result of a to the power of b.", hints: ["Use ** operator", "a ** b"], expectedOutput: "64", difficulty: "Medium", dataTypesRequired: ["variable", "multiple", "print"] },
      { instructions: "Create x = 17 and y = 5. Print the remainder of x divided by y.", hints: ["Use the % operator", "x % y"], expectedOutput: "2", difficulty: "Medium", dataTypesRequired: ["variable", "divide", "print"] },
      { instructions: "Create a = 10. Print the result of checking if a equals 10.", hints: ["print(a == 10)"], expectedOutput: "True", difficulty: "Easy", dataTypesRequired: ["variable", "equal", "print"] },
      { instructions: "Create x = 5 and y = 8. Print the result of checking if x is not equal to y.", hints: ["print(x != y)"], expectedOutput: "True", difficulty: "Easy", dataTypesRequired: ["variable", "notequal", "print"] },
      { instructions: "Create a = 3 and b = 9. Print the result of checking if a is less than b.", hints: ["print(a < b)"], expectedOutput: "True", difficulty: "Easy", dataTypesRequired: ["variable", "less", "print"] },
      { instructions: "Create x = 7 and y = 7. Print the result of checking if x is less than or equal to y.", hints: ["print(x <= y)"], expectedOutput: "True", difficulty: "Easy", dataTypesRequired: ["variable", "lessequal", "print"] },
      { instructions: "Create a = 15 and b = 9. Print the result of checking if a is greater than b.", hints: ["print(a > b)"], expectedOutput: "True", difficulty: "Easy", dataTypesRequired: ["variable", "greater", "print"] },
      { instructions: "Create x = 6 and y = 6. Print the result of checking if x is greater than or equal to y.", hints: ["print(x >= y)"], expectedOutput: "True", difficulty: "Easy", dataTypesRequired: ["variable", "greaterequal", "print"] },
      { instructions: "Create a = 4 and b = 5. Print the result of checking if a equals b.", hints: ["print(a == b)"], expectedOutput: "False", difficulty: "Easy", dataTypesRequired: ["variable", "equal", "print"] },
      { instructions: "Create total = 50. Add 25 to total using +=. Print total.", hints: ["total += 25", "print(total)"], expectedOutput: "75", difficulty: "Medium", dataTypesRequired: ["variable", "add", "print"] },
      { instructions: "Create score = 100. Subtract 35 from score using -=. Print score.", hints: ["score -= 35"], expectedOutput: "65", difficulty: "Medium", dataTypesRequired: ["variable", "subtract", "print"] },
      { instructions: "Create a = 3 and b = 7. Print the result of a + b.", hints: ["print(a + b)"], expectedOutput: "10", difficulty: "Easy", dataTypesRequired: ["variable", "add", "print"] },
      { instructions: "Create width = 8 and height = 5. Print the area (width * height).", hints: ["area = width * height"], expectedOutput: "40", difficulty: "Easy", dataTypesRequired: ["variable", "multiple", "print"] },
      { instructions: "Create x = 100 and y = 25. Print x divided by y.", hints: ["print(x / y)"], expectedOutput: "4.0", difficulty: "Easy", dataTypesRequired: ["variable", "divide", "print"] },
      { instructions: "Create a = 13 and b = 4. Print the floor division of a by b.", hints: ["a // b gives whole number", "print(a // b)"], expectedOutput: "3", difficulty: "Medium", dataTypesRequired: ["variable", "divide", "print"] },
      { instructions: "Create x = 9 and y = 2. Print the result of checking if x is greater than y.", hints: ["print(x > y)"], expectedOutput: "True", difficulty: "Easy", dataTypesRequired: ["variable", "greater", "print"] },
      { instructions: "Create a = 5 and b = 10. Print the result of checking if a is greater than b.", hints: ["print(a > b)"], expectedOutput: "False", difficulty: "Easy", dataTypesRequired: ["variable", "greater", "print"] },
      { instructions: "Create num = 12. Print the result of num % 5.", hints: ["The % operator gives the remainder"], expectedOutput: "2", difficulty: "Medium", dataTypesRequired: ["variable", "divide", "print"] },
      { instructions: "Create a = 2 and b = 10. Print the result of a * b.", hints: ["print(a * b)"], expectedOutput: "20", difficulty: "Easy", dataTypesRequired: ["variable", "multiple", "print"] },
      { instructions: "Create x = 50 and y = 50. Print the result of checking if x equals y.", hints: ["print(x == y)"], expectedOutput: "True", difficulty: "Easy", dataTypesRequired: ["variable", "equal", "print"] },
      { instructions: "Create a = 7 and b = 3. Print the result of a - b.", hints: ["print(a - b)"], expectedOutput: "4", difficulty: "Easy", dataTypesRequired: ["variable", "subtract", "print"] },
    ],
  },

  // ── MODULE 3: Conditionals ────────────────────────────────
  {
    lessonKey: "Conditionals",
    title: "Conditionals – Question Bank",
    timeLimit: 600,
    questions: [
      { instructions: "Create age = 20. If age >= 18, print Adult.", hints: ["if age >= 18:", "    print('Adult')"], expectedOutput: "Adult", difficulty: "Easy", dataTypesRequired: ["variable", "if", "greaterequal", "print"] },
      { instructions: "Create score = 45. If score >= 50 print Pass, else print Fail.", hints: ["if score >= 50:", "else:"], expectedOutput: "Fail", difficulty: "Easy", dataTypesRequired: ["variable", "if", "else", "greaterequal", "print"] },
      { instructions: "Create num = 8. If num % 2 == 0 print Even, else print Odd.", hints: ["Use %", "if num % 2 == 0:"], expectedOutput: "Even", difficulty: "Medium", dataTypesRequired: ["variable", "if", "else", "equal", "print"] },
      { instructions: "Create x = 0. If x > 0 print Positive. elif x < 0 print Negative. else print Zero.", hints: ["Three branches: if, elif, else"], expectedOutput: "Zero", difficulty: "Medium", dataTypesRequired: ["variable", "if", "elif", "else", "greater", "less", "print"] },
      { instructions: "Create temp = 35. If temp >= 30 print Hot. elif temp >= 20 print Warm. else print Cold.", hints: ["Check highest first"], expectedOutput: "Hot", difficulty: "Medium", dataTypesRequired: ["variable", "if", "elif", "else", "greaterequal", "print"] },
      { instructions: "Create grade = 91. If grade >= 90 print A. elif grade >= 80 print B. else print C.", hints: ["if, elif, else"], expectedOutput: "A", difficulty: "Medium", dataTypesRequired: ["variable", "if", "elif", "else", "greaterequal", "print"] },
      { instructions: "Create n = 7. If n > 10 print Big. else print Small.", hints: ["if n > 10:"], expectedOutput: "Small", difficulty: "Easy", dataTypesRequired: ["variable", "if", "else", "greater", "print"] },
      { instructions: "Create a = 5 and b = 5. If a == b print Equal. else print Not Equal.", hints: ["if a == b:"], expectedOutput: "Equal", difficulty: "Easy", dataTypesRequired: ["variable", "if", "else", "equal", "print"] },
      { instructions: "Create age = 15. If age >= 18 print Can vote. else print Too young.", hints: ["if age >= 18:"], expectedOutput: "Too young", difficulty: "Easy", dataTypesRequired: ["variable", "if", "else", "greaterequal", "print"] },
      { instructions: "Create score = 75. If score >= 90 print Excellent. elif score >= 75 print Good. else print Average.", hints: ["Check conditions in order"], expectedOutput: "Good", difficulty: "Medium", dataTypesRequired: ["variable", "if", "elif", "else", "greaterequal", "print"] },
      { instructions: "Create x = 10 and y = 20. If x > y print x wins. else print y wins.", hints: ["if x > y:"], expectedOutput: "y wins", difficulty: "Easy", dataTypesRequired: ["variable", "if", "else", "greater", "print"] },
      { instructions: "Create num = 3. If num != 5 print Not five.", hints: ["if num != 5:", "!= means not equal"], expectedOutput: "Not five", difficulty: "Easy", dataTypesRequired: ["variable", "if", "notequal", "print"] },
      { instructions: "Create speed = 60. If speed > 100 print Overspeed. elif speed > 60 print Fast. else print Normal.", hints: ["Check from highest to lowest"], expectedOutput: "Normal", difficulty: "Medium", dataTypesRequired: ["variable", "if", "elif", "else", "greater", "print"] },
      { instructions: "Create value = 0. If value == 0 print Zero. elif value > 0 print Positive. else print Negative.", hints: ["Order of conditions matters"], expectedOutput: "Zero", difficulty: "Medium", dataTypesRequired: ["variable", "if", "elif", "else", "equal", "greater", "print"] },
      { instructions: "Create marks = 100. If marks == 100 print Perfect Score.", hints: ["if marks == 100:"], expectedOutput: "Perfect Score", difficulty: "Easy", dataTypesRequired: ["variable", "if", "equal", "print"] },
      { instructions: "Create a = 4 and b = 8. If a < b print a is smaller. else print b is smaller.", hints: ["if a < b:"], expectedOutput: "a is smaller", difficulty: "Easy", dataTypesRequired: ["variable", "if", "else", "less", "print"] },
      { instructions: "Create n = 15. If n % 3 == 0 print Divisible by 3. else print Not divisible.", hints: ["n % 3 checks divisibility"], expectedOutput: "Divisible by 3", difficulty: "Medium", dataTypesRequired: ["variable", "if", "else", "equal", "print"] },
      { instructions: "Create age = 65. If age >= 60 print Senior. elif age >= 18 print Adult. else print Minor.", hints: ["Senior check must come first"], expectedOutput: "Senior", difficulty: "Medium", dataTypesRequired: ["variable", "if", "elif", "else", "greaterequal", "print"] },
      { instructions: "Create x = 5. If x <= 5 print At most five.", hints: ["if x <= 5:", "<= is less than or equal"], expectedOutput: "At most five", difficulty: "Easy", dataTypesRequired: ["variable", "if", "lessequal", "print"] },
      { instructions: "Create score = 50. If score >= 50 print Pass. else print Fail.", hints: ["Boundary condition: 50 should print Pass"], expectedOutput: "Pass", difficulty: "Easy", dataTypesRequired: ["variable", "if", "else", "greaterequal", "print"] },
      { instructions: "Create num = 12. If num % 2 == 0 print Even. else print Odd.", hints: ["% gives remainder", "if num % 2 == 0"], expectedOutput: "Even", difficulty: "Medium", dataTypesRequired: ["variable", "if", "else", "equal", "print"] },
      { instructions: "Create rain = True. If rain == True print Bring umbrella. else print Sunny day.", hints: ["if rain == True:"], expectedOutput: "Bring umbrella", difficulty: "Medium", dataTypesRequired: ["variable", "if", "else", "equal", "print"] },
      { instructions: "Create score = 60. If score >= 90 print A. elif score >= 80 print B. elif score >= 70 print C. elif score >= 60 print D. else print F.", hints: ["Check each threshold in order"], expectedOutput: "D", difficulty: "Hard", dataTypesRequired: ["variable", "if", "elif", "else", "greaterequal", "print"] },
      { instructions: "Create a = 10 and b = 10. If a >= b print Not less. else print Less.", hints: ["a >= b is True when equal"], expectedOutput: "Not less", difficulty: "Medium", dataTypesRequired: ["variable", "if", "else", "greaterequal", "print"] },
      { instructions: "Create n = 2. If n > 1 print Greater than one.", hints: ["if n > 1:"], expectedOutput: "Greater than one", difficulty: "Easy", dataTypesRequired: ["variable", "if", "greater", "print"] },
    ],
  },

  // ── MODULE 4: Loops ───────────────────────────────────────
  {
    lessonKey: "Loops",
    title: "Loops – Question Bank",
    timeLimit: 600,
    questions: [
      { instructions: "Use a while loop to print numbers 1 to 3, each on a new line.", hints: ["i = 1", "while i <= 3: print(i), i += 1"], expectedOutput: "1\n2\n3", difficulty: "Easy", dataTypesRequired: ["variable", "while", "lessequal", "print"] },
      { instructions: "Use a while loop to print numbers 1 to 5, each on a new line.", hints: ["i = 1", "while i <= 5:"], expectedOutput: "1\n2\n3\n4\n5", difficulty: "Easy", dataTypesRequired: ["variable", "while", "lessequal", "print"] },
      { instructions: "Use a while loop to print the word Go exactly 3 times.", hints: ["count = 0", "while count < 3: print('Go'), count += 1"], expectedOutput: "Go\nGo\nGo", difficulty: "Easy", dataTypesRequired: ["variable", "while", "less", "print"] },
      { instructions: "Use a while loop to count down from 5 to 1 and print each number.", hints: ["i = 5", "while i > 0: print(i), i -= 1"], expectedOutput: "5\n4\n3\n2\n1", difficulty: "Easy", dataTypesRequired: ["variable", "while", "greater", "print"] },
      { instructions: "Use a while loop to print even numbers from 2 to 10.", hints: ["i = 2", "while i <= 10: print(i), i += 2"], expectedOutput: "2\n4\n6\n8\n10", difficulty: "Medium", dataTypesRequired: ["variable", "while", "lessequal", "add", "print"] },
      { instructions: "Use a while loop to calculate the sum of 1 + 2 + 3 + 4 + 5. Print the total.", hints: ["total = 0, i = 1", "while i <= 5: total += i, i += 1", "print(total)"], expectedOutput: "15", difficulty: "Medium", dataTypesRequired: ["variable", "while", "add", "lessequal", "print"] },
      { instructions: "Use a while loop to print odd numbers from 1 to 9.", hints: ["i = 1", "while i <= 9: print(i), i += 2"], expectedOutput: "1\n3\n5\n7\n9", difficulty: "Medium", dataTypesRequired: ["variable", "while", "lessequal", "print"] },
      { instructions: "Use a while loop starting at i = 10. While i >= 8, print i and subtract 1.", hints: ["while i >= 8:"], expectedOutput: "10\n9\n8", difficulty: "Easy", dataTypesRequired: ["variable", "while", "greaterequal", "print"] },
      { instructions: "Use a while loop to print the number 7 exactly 4 times.", hints: ["count = 0", "while count < 4: print(7), count += 1"], expectedOutput: "7\n7\n7\n7", difficulty: "Easy", dataTypesRequired: ["variable", "while", "less", "print"] },
      { instructions: "Use a while loop to calculate 2 * 1 * 2 * 3 * 4 (product of 1 to 4). Print result.", hints: ["result = 1, i = 1", "while i <= 4: result *= i"], expectedOutput: "24", difficulty: "Hard", dataTypesRequired: ["variable", "while", "multiple", "lessequal", "print"] },
      { instructions: "Use a while loop to print multiples of 3 from 3 to 15.", hints: ["i = 3", "while i <= 15: print(i), i += 3"], expectedOutput: "3\n6\n9\n12\n15", difficulty: "Medium", dataTypesRequired: ["variable", "while", "lessequal", "add", "print"] },
      { instructions: "Use a while loop to print numbers 0 to 4.", hints: ["i = 0", "while i < 5: print(i), i += 1"], expectedOutput: "0\n1\n2\n3\n4", difficulty: "Easy", dataTypesRequired: ["variable", "while", "less", "print"] },
      { instructions: "Use a while loop to sum numbers from 1 to 10. Print the total.", hints: ["total = 0, i = 1", "while i <= 10:"], expectedOutput: "55", difficulty: "Medium", dataTypesRequired: ["variable", "while", "add", "lessequal", "print"] },
      { instructions: "Use a while loop to print Hello 5 times.", hints: ["count = 0", "while count < 5: print('Hello'), count += 1"], expectedOutput: "Hello\nHello\nHello\nHello\nHello", difficulty: "Easy", dataTypesRequired: ["variable", "while", "less", "print"] },
      { instructions: "Use a while loop. Start i = 1. While i <= 4, print i * 2 and increment i.", hints: ["print(i * 2)", "i += 1"], expectedOutput: "2\n4\n6\n8", difficulty: "Medium", dataTypesRequired: ["variable", "while", "multiple", "lessequal", "print"] },
      { instructions: "Use a while loop to count from 10 down to 6. Print each number.", hints: ["i = 10", "while i >= 6: print(i), i -= 1"], expectedOutput: "10\n9\n8\n7\n6", difficulty: "Easy", dataTypesRequired: ["variable", "while", "greaterequal", "print"] },
      { instructions: "Use a while loop. Print numbers 1 to 6 but skip printing 4 (add 1 to i always, print only if i != 4).", hints: ["inside loop: if i != 4: print(i)", "Always increment i"], expectedOutput: "1\n2\n3\n5\n6", difficulty: "Hard", dataTypesRequired: ["variable", "while", "if", "notequal", "lessequal", "print"] },
      { instructions: "Use a while loop. i starts at 1. While i < 6, if i is even print Even, else print Odd. Then increment i.", hints: ["if i % 2 == 0: print('Even')", "else: print('Odd')"], expectedOutput: "Odd\nEven\nOdd\nEven\nOdd", difficulty: "Hard", dataTypesRequired: ["variable", "while", "if", "else", "equal", "less", "print"] },
      { instructions: "Use a while loop to print the squares of numbers 1 to 4.", hints: ["print(i ** 2)", "i goes from 1 to 4"], expectedOutput: "1\n4\n9\n16", difficulty: "Medium", dataTypesRequired: ["variable", "while", "multiple", "lessequal", "print"] },
      { instructions: "Use a while loop. Start total = 100. Subtract 20 each iteration while total > 0. Print total each time.", hints: ["while total > 0: print(total), total -= 20"], expectedOutput: "100\n80\n60\n40\n20", difficulty: "Medium", dataTypesRequired: ["variable", "while", "subtract", "greater", "print"] },
      { instructions: "Use a while loop. i starts at 1. While i <= 5, print i + 10 and increment i.", hints: ["print(i + 10)"], expectedOutput: "11\n12\n13\n14\n15", difficulty: "Medium", dataTypesRequired: ["variable", "while", "add", "lessequal", "print"] },
      { instructions: "Use a while loop to print numbers 2, 4, 6. Start i = 2, while i <= 6, print i and add 2.", hints: ["i += 2 each iteration"], expectedOutput: "2\n4\n6", difficulty: "Easy", dataTypesRequired: ["variable", "while", "add", "lessequal", "print"] },
      { instructions: "Use a while loop. Start count = 3. While count > 0, print count then subtract 1. Then print Blastoff!", hints: ["Loop prints 3 2 1, then after loop print Blastoff!"], expectedOutput: "3\n2\n1\nBlastoff!", difficulty: "Medium", dataTypesRequired: ["variable", "while", "subtract", "greater", "print"] },
      { instructions: "Use a while loop to find the sum of even numbers from 2 to 8. Print the sum.", hints: ["i = 2", "while i <= 8: total += i, i += 2", "2+4+6+8 = 20"], expectedOutput: "20", difficulty: "Hard", dataTypesRequired: ["variable", "while", "add", "lessequal", "print"] },
      { instructions: "Use a while loop. i starts at 1. While i <= 3, print the word Line followed by i (e.g. Line 1).", hints: ["print('Line', i)"], expectedOutput: "Line 1\nLine 2\nLine 3", difficulty: "Medium", dataTypesRequired: ["variable", "while", "lessequal", "print"] },
    ],
  },
];